# Generated by workspace - do not edit manually
from pathlib import Path

import pytest

ACTUAL_DIR = Path(__file__).parent / "plan_snapshots_actual"
EXPECTED_DIR = Path(__file__).parent / "plan_snapshots"

TEST_CASES = [
    "backup_export_mongodbatlas_cloud_provider_access_setup_this[0]",
    "backup_export_mongodbatlas_cloud_provider_access_authorization_this[0]",
    "backup_export_module_backup_export[0]_azurerm_storage_account_atlas[0]",
    "backup_export_module_backup_export[0]_azurerm_storage_container_atlas[0]",
    "backup_export_module_backup_export[0]_azurerm_role_assignment_backup_export",
    "backup_export_module_backup_export[0]_mongodbatlas_cloud_backup_snapshot_export_bucket_this",
]


@pytest.mark.parametrize("name", TEST_CASES)
def test_plan_snapshot(name: str, file_regression) -> None:
    actual_file = ACTUAL_DIR / f"{name}.yaml"
    expected_file = EXPECTED_DIR / f"{name}.yaml"
    assert actual_file.exists(), f'Actual file not found: {actual_file}'
    file_regression.check(actual_file.read_text(), fullpath=expected_file)
